#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mast
Version  : 1.4.0
Release  : 6
URL      : https://rubygems.org/downloads/mast-1.4.0.gem
Source0  : https://rubygems.org/downloads/mast-1.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-mast-bin
BuildRequires : ruby
BuildRequires : rubygem-detroit
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
= Mast
___
.-----'---'-.
|           |
|           |
|           |
'-----------'

%package bin
Summary: bin components for the rubygem-mast package.
Group: Binaries

%description bin
bin components for the rubygem-mast package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mast-1.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-mast.gemspec

%build
gem build rubygem-mast.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mast-1.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/mast-1.4.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/.ruby
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/COPYING.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/HISTORY.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/QED.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/bin/mast
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/lib/mast.rb
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/lib/mast.yml
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/lib/mast/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/lib/mast/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/lib/mast/manifest.rb
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/lib/plugins/syckle/mast.rb
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/man/man1/index.txt
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/man/man1/mast.1
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/man/man1/mast.1.html
/usr/lib64/ruby/gems/2.3.0/gems/mast-1.4.0/man/man1/mast.1.ronn
/usr/lib64/ruby/gems/2.3.0/specifications/mast-1.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/mast
