#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mast
Version  : 1.4.0
Release  : 4
URL      : https://rubygems.org/downloads/mast-1.4.0.gem
Source0  : https://rubygems.org/downloads/mast-1.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-mast-bin
BuildRequires : ruby
BuildRequires : rubygem-detroit
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
= Mast
___
.-----'---'-.
|           |
|           |
|           |
'-----------'

%package bin
Summary: bin components for the rubygem-mast package.
Group: Binaries

%description bin
bin components for the rubygem-mast package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mast-1.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-mast.gemspec

%build
gem build rubygem-mast.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mast-1.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/mast-1.4.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Dir/cdesc-Dir.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/File/cdesc-File.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/ask-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/cdesc-Cli.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/clean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/confirm_clean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/confirm_clobber-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/manifest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/new-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/old-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/option_parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/quiet%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/quiet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/recent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_cancelled-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_created-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_difference-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_manifest_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_outofdate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_overwrite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_updated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_verify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_warn_shadowing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_whatsnew-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/report_whatsold-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/run_command-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/up-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Cli/verify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/all%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/bang%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/bang-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/cdesc-Manifest.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/change_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/changed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/chart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/checksum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/clean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/cleanlist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/create_temporary_manifest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/diff-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/digester-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/dir%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/dir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/directory-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/exclude-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/exclusions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/filechart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/filelist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/files-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/headless%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/headless-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/ignores-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/include%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/inclusions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/io-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/list_without_folders-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/listing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/open-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/parse_directory-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/parse_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/parse_topline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/read%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/read_topline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/rec_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/showlist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/topline_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/unlisted-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/verify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/whatsnew-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/Manifest/whatsold-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/cdesc-Mast.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Mast/metadata-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/cdesc-Mast.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/clean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/exclude-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/include-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/initialize_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/manifest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/Mast/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/Plugins/cdesc-Plugins.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/Syckle/cdesc-Syckle.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/page-COPYING_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/page-HISTORY_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/page-QED_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/mast-1.4.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/.ruby
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/COPYING.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/HISTORY.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/QED.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/bin/mast
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/lib/mast.rb
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/lib/mast.yml
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/lib/mast/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/lib/mast/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/lib/mast/manifest.rb
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/lib/plugins/syckle/mast.rb
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/man/man1/index.txt
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/man/man1/mast.1
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/man/man1/mast.1.html
/usr/lib64/ruby/gems/2.2.0/gems/mast-1.4.0/man/man1/mast.1.ronn
/usr/lib64/ruby/gems/2.2.0/specifications/mast-1.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/mast
